CREATE_ALERTS_TABLE = """
CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    attack_type TEXT NOT NULL,
    src_ip TEXT NOT NULL,
    details TEXT,
    status TEXT DEFAULT 'BLOCKED'
);
"""

CREATE_INDEX_SRC_IP = """
CREATE INDEX IF NOT EXISTS idx_alerts_src_ip ON alerts(src_ip);
"""
